version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: ./dist
          ignore: 
            - node_modules
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:latest
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: